repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: debug-statements
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # - id: no-commit-to-branch
      #   args:
      #     - --branch
      #     - main
      #     - --branch
      #     - master
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.5
    hooks:
    -   id: reorder-python-imports
        args: [
            --application-directories, '.:src',
            --py37-plus,
            --add-import, 'from __future__ import annotations',
        ]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
