[tool.flake8]
max-line-length = 88
ignore = ["E111", "W503"]
exclude = ["*.md", "*.toml", "*.yaml", "*.json", "pipfile*", "LICENSE", "makefile", ".*", "scrap*"]

[tool.autopep8]
max_line_length = 88
in-place = true
recursive = true
aggressive = 3

[tool.black]
line-length = 88
